[package]
name = "ftpserver"
version = "0.1.0"
authors = ["jacobweir"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libunftp = "0.14.1"
tokio = { version = "0.3", features=["full"] }